// Combat engine for Knight Golf inter-hole battles (pure logic).
import { ZONE_RANK } from '../core/shots.js';
import { ultimateFor } from './heraldry.js';

/**
 * Resolve combat beats for Castle Conquest and Dueling Knighthood.
 * Returns { beats, events }
 */
export function resolveDuel(game, results, modeId) {
  const players = game.players;
  const beats = [];
  const events = [];
  const state = game.modeState;

  if (players.length < 2) return { beats, events };

  // Score ranking for this hole
  const scored = players.map((p) => {
    const res = results[p.id] || { strokes: 4, bestZone: 'fairway', holed: false, birdie: false, bullseyes: 0 };
    const zRank = ZONE_RANK[res.bestZone] ?? 5;
    // In Dueling Knighthood, lower strokes is king; in Castle, best zone / points
    const power = modeId === 'duel' ? (10 - res.strokes) * 10 + zRank : zRank * 20 + (10 - res.strokes);
    return { player: p, res, power, zRank };
  });

  scored.sort((a, b) => b.power - a.power);
  const best = scored[0];
  const second = scored[1];

  // Tie check
  if (best.power === second.power && best.power > 0) {
    beats.push({
      attacker: best.player,
      defender: second.player,
      kind: 'clash',
      dmg: 10,
      text: `${best.player.name} & ${second.player.name} lock shields in a furious clash!`,
    });
    events.push({ t: 'sfx', name: 'shieldClash' });
    events.push({ t: 'banner', text: 'SHIELD CLASH!', sub: 'Equal accuracy!', color: '#ff9f43' });
    events.push({ t: 'shake', mag: 12 });
    return { beats, events };
  }

  // Best player executes attack on opponents
  const atk = best.player;
  const isBirdieOrBullseye = best.res.birdie || best.res.bullseyes > 0;
  const ult = ultimateFor(atk);

  for (let i = 1; i < scored.length; i++) {
    const def = scored[i].player;
    const defState = state.players?.[def.id] || {};
    let baseDmg = modeId === 'duel' ? Math.max(15, (scored[i].res.strokes - best.res.strokes) * 15 + 10) : 25;
    
    // Cracked armor penalty
    if (defState.crackedArmor) {
      baseDmg = Math.round(baseDmg * 1.5);
      defState.crackedArmor = false;
    }

    if (isBirdieOrBullseye) {
      const dmg = baseDmg + 20;
      beats.push({
        attacker: atk,
        defender: def,
        kind: ult.kind,
        dmg,
        text: `${atk.name} invokes ${ult.name} for ${dmg} CRITICAL damage!`,
      });
      events.push({ t: 'sfx', name: ult.kind === 'flame' ? 'flame' : 'lightning' });
      events.push({ t: 'banner', text: `${ult.name.toUpperCase()}!`, sub: `${atk.name} strikes ${def.name}!`, color: '#e74c3c' });
    } else {
      beats.push({
        attacker: atk,
        defender: def,
        kind: 'crit',
        dmg: baseDmg,
        text: `${atk.name} lands a crushing blow on ${def.name} for ${baseDmg} damage!`,
      });
      events.push({ t: 'sfx', name: 'crit' });
      events.push({ t: 'banner', text: 'CRITICAL STRIKE!', sub: `${atk.name} dominates the hole!`, color: '#f4c55a' });
    }

    // Apply damage to HP
    if (state.players && state.players[def.id]) {
      state.players[def.id].hp = Math.max(0, (state.players[def.id].hp ?? 100) - baseDmg);
      if (state.players[def.id].hp === 0) {
        beats.push({
          attacker: atk,
          defender: def,
          kind: 'unhorse',
          dmg: 0,
          text: `${def.name} has been UNHORSED!`,
        });
        events.push({ t: 'sfx', name: 'defeat' });
        events.push({ t: 'banner', text: 'UNHORSED!', sub: `${def.name} is knocked down!`, color: '#ff3b30' });
      }
    }
  }

  events.push({ t: 'shake', mag: 14 });
  return { beats, events };
}

/**
 * Resolve combat beats for Raid Boss mode.
 */
export function resolveRaidBoss(game, results) {
  const beats = [];
  const events = [];
  const state = game.modeState;
  const players = game.players;

  // Total points generated by the foursome this hole
  let teamPower = 0;
  let hazardsHit = 0;

  for (const p of players) {
    const res = results[p.id];
    if (res) {
      teamPower += (res.bullseyes * 40) + (res.fairwayHit ? 20 : 0) + (res.holed ? 50 : 20);
      if (res.sand > 0 || res.water > 0 || res.ob > 0) hazardsHit++;
    }
  }

  const bossDmg = Math.max(25, teamPower);
  state.bossHp = Math.max(0, (state.bossHp ?? 500) - bossDmg);

  beats.push({
    attacker: players[0],
    defender: { name: state.bossName || 'Goliath Dragon', id: 'boss' },
    kind: teamPower > 80 ? 'flame' : 'crit',
    dmg: bossDmg,
    text: `The party rallies and strikes ${state.bossName || 'the Boss'} for ${bossDmg} damage!`,
  });

  events.push({ t: 'sfx', name: teamPower > 80 ? 'lightning' : 'crit' });
  events.push({ t: 'banner', text: 'RAID STRIKE!', sub: `Party dealt ${bossDmg} dmg!`, color: '#f4c55a' });

  // Dragon counter-attack if hazards were hit
  if (hazardsHit > 0 && state.bossHp > 0) {
    const counterDmg = hazardsHit * 15;
    for (const p of players) {
      if (state.players?.[p.id]) {
        state.players[p.id].hp = Math.max(0, (state.players[p.id].hp ?? 100) - counterDmg);
      }
    }
    beats.push({
      attacker: { name: state.bossName || 'Goliath Dragon', id: 'boss' },
      defender: players[0],
      kind: 'boss',
      dmg: counterDmg,
      text: `${state.bossName || 'The Dragon'} unleashes an infernal roar, burning the party for ${counterDmg} damage!`,
    });
    events.push({ t: 'sfx', name: 'dragonRoar' });
    events.push({ t: 'shake', mag: 16 });
  }

  if (state.bossHp === 0) {
    events.push({ t: 'sfx', name: 'fanfare' });
    events.push({ t: 'banner', text: 'BOSS SLAIN!', sub: 'Camelot is Saved!', color: '#2ecc71' });
  }

  return { beats, events };
}
